<?php
/**
 * Bold checkout self-hosted template.
 *
 * @var Bold\CheckoutSelfHosted\Block\Checkout $this
 */
/** @var Magento\Framework\Escaper $escaper */
try {
    $orderData = $this->getOrderData();
    $orderId = $this->getPublicOrderId();
} catch (Exception $e) {
    echo '<script>window.location.href = "' . $escaper->escapeUrl($this->getReturnUrl()) . '"</script>';
    return;
}
?>
<script>
    window.shopAlias = "<?php echo $escaper->escapeJs($this->getShopAlias()) ?>";
    window.customDomain = "<?php echo $escaper->escapeJs($this->getCustomDomain()) ?>";
    window.shopName = "<?php echo $escaper->escapeJs($this->getShopName()) ?>";
    window.returnUrl = "<?php echo $escaper->escapeJs($this->getReturnUrl()) ?>";
    window.loginUrl = "<?php echo $escaper->escapeJs($this->getLoginUrl()) ?>";
    window.headerLogoUrl = "<?php echo $escaper->escapeJs($this->getHeaderLogoUrl()) ?>";
    window.platformType = "bold_platform";
    window.environment = {
        type: "production",
    };
    window.initializedOrder = {
        data: <?php echo $orderData; ?>
    };
    window.publicOrderId = "<?php echo $escaper->escapeJs($orderId) ?>";
    window.shopIdentifier = "<?php echo $escaper->escapeJs($this->getShopIdentifier()) ?>";
    window.initializedOrder = <?php echo $orderData ?>;
</script>
<div id='main'>
    <script src="<?php echo $escaper->escapeUrl($this->getCheckoutTemplateScriptUrl()) ?>"></script>
</div>
<footer></footer>
